/*
 * This file is generated by jOOQ.
 */
package com.shf.jooq.db;


import com.shf.jooq.tables.Author;
import com.shf.jooq.tables.AuthorBook;
import com.shf.jooq.tables.Book;
import com.shf.jooq.tables.Sample;
import com.shf.jooq.tables.User;
import com.shf.jooq.tables.Users;


/**
 * Convenience access to all tables in demo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demo.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>demo.author_book</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>demo.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>demo.sample</code>.
     */
    public static final Sample SAMPLE = Sample.SAMPLE;

    /**
     * The table <code>demo.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>demo.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
